from __future__ import annotations

import io
from pathlib import Path

import streamlit as st
from PIL import Image

from src.adaptive_compressor import AdaptiveImageCompressor


st.set_page_config(page_title="Adaptive Image Compressor", layout="wide")
st.title("Adaptive Image Compression and Resizing Studio")

if "compressor" not in st.session_state:
    st.session_state.compressor = AdaptiveImageCompressor()

uploaded_file = st.file_uploader("Upload an image to compress", type=["png", "jpg", "jpeg", "webp", "bmp"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    target_kb = st.slider("Target output size (KB)", min_value=20, max_value=2000, value=200, step=10)

    if st.button("Compress and resize image"):
        with st.spinner("Analyzing the image and optimizing the resize and quality settings..."):
            result = st.session_state.compressor.compress(image, float(target_kb))

        st.subheader("Original vs resized and compressed output")
        col1, col2 = st.columns(2)
        with col1:
            st.image(image, caption=f"Original image ({image.size[0]} × {image.size[1]})", use_container_width=True)
        with col2:
            st.image(result["image"], caption=f"Compressed output ({result['compressed_shape'][1]} × {result['compressed_shape'][0]})", use_container_width=True)

        st.subheader("Compression summary")
        st.write({
            "Predicted resize factor": round(result["resize_factor"], 4),
            "Predicted JPEG quality": result["quality"],
            "Resized output dimensions": f"{result['resized_shape'][1]} × {result['resized_shape'][0]}",
            "Target size (KB)": round(result["target_size_kb"], 2),
            "Actual size (KB)": round(result["actual_size_kb"], 2),
            "SSIM": round(result["ssim"], 4),
            "PSNR (dB)": round(result["psnr"], 2),
            "MSE": round(result["mse"], 4),
        })

        st.subheader("Download outputs")
        resized_buffer = io.BytesIO()
        result["resized_image"].save(resized_buffer, format="PNG")
        compressed_buffer = io.BytesIO()
        result["image"].save(compressed_buffer, format="JPEG", quality=result["quality"])

        download_cols = st.columns(2)
        with download_cols[0]:
            st.download_button(
                label="Download resized image",
                data=resized_buffer.getvalue(),
                file_name=f"{uploaded_file.name.rsplit('.', 1)[0]}_resized.png",
                mime="image/png",
            )
        with download_cols[1]:
            st.download_button(
                label="Download compressed image",
                data=compressed_buffer.getvalue(),
                file_name=f"{uploaded_file.name.rsplit('.', 1)[0]}_compressed.jpg",
                mime="image/jpeg",
            )
else:
    st.info("Upload an image to begin the compression workflow.")

st.markdown("""
### Project goals

This app predicts the optimal resize and JPEG quality for a source image based on its visual characteristics and the target output size. It helps preserve the most useful detail while keeping the final file within the chosen size limit.

### Quality metrics used

- SSIM: structural similarity index
- PSNR: peak signal-to-noise ratio
- MSE: mean squared error

### Output options

- Download the resized image generated by the ML-driven resize step
- Download the optimized compressed image ready for sharing or storage
""")
